server:
  port: 8080
  undertow:
    threads:
      worker: 16
    buffer-size: 1024
    direct-buffers: true
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
# enabled debug log out.
logging:
  level:
    com:
      alibaba:
        dashscope:
          api: debug
    org:
      apache:
        http: debug
      springframework:
        ai: debug
        web:
          client:
            RestTemplate: debug
    root: info
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG

# 强制设置HTTP响应头
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    view:
      prefix: /views/
      suffix: .html
  # 启用跨域支持
    cors:
      allowed-origins: '*'
      allowed-methods: 'GET,POST'


  main:
    allow-bean-definition-overriding: true
  application:
    name: ai
  data:
    redis:
      host: 127.0.0.1
      port: 16379
      password: huadingyun
      database: 0

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/documents?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: huading123
    type: com.alibaba.druid.pool.DruidDataSource

  ai:
    #    ollama:
    #      base-url: http://localhost:11434
    #      # 聊天模型配置
    #      chat:
    #        model: deepseek-r1:14b
    #        options:
    #          temperature: 0.7
    #      # 嵌入模型配置
    #      embedding:
    #base-url: http://localhost:11434
    #          model: nomic-embed-text:latest
    dashscope:
      # sk-5b2e76ac7cbf483095543c7831d89c94
      #
      api-key: sk-45da0f0c3cb94953beb8e8b296b37543
      #      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      chat:
        options:
          model: qwen3-32b
          #128k长上下文的推理模型
#          enable-search: true
          #是否允许联网查询

      embedding:
        api-key: sk-45da0f0c3cb94953beb8e8b296b37543
        options:
          model: text-embedding-v3
          dimensions: 1024

    # 向量存储器配置
    vectorstore:
      milvus:
        client:
          host: ${MILVUS_HOST:localhost} # default: localhost
          port: ${MILVUS_PORT:19530} # default: 19530
          username: ${MILVUS_USERNAME:huading} # default: root
          password: ${MILVUS_PASSWORD:hdadmin} # default: milvus
        databaseName: ${MILVUS_DATABASE_NAME:test} # default: default
        collectionName: ${MILVUS_COLLECTION_NAME:vector_store} # default: vector_store
        embeddingDimension: 1024 # default: 1536 大约2000字content限制
        indexType: IVF_FLAT # default: IVF_FLAT
        metricType: COSINE # default: COSINE
        initialize-schema: true
        auto-id: false

mybatis-plus:
  #  mapper-locations: classpath:/mapper/**/*.xml  # Mapper XML文件位置
  type-aliases-package: com.hd.ai.rag.domain  # 类型别名包名，例如实体类的包名
  global-config:
    db-config:
      db-type: mysql  # 数据库类型，用于生成SQL时进行优化等处理
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启SQL日志输出，方便调试



milvus:
  host: ${MILVUS_HOST:localhost} # default: localhost
  port: ${MILVUS_PORT:19530} # default: 19530
  username: ${MILVUS_USERNAME:huading} # default: root
  password: ${MILVUS_PASSWORD:hdadmin} # default: milvus

workspace:
  root: D:\workspace\hdy-erp

